coverage:
  status:
    project:
      default:
        # Set to informational so project coverage doesn't fail CI
        informational: true
    patch:
      default:
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true
