"""Add blob_processing_attempt table

Revision ID: 758d4879be2e
Revises: 34a9930bd1f7
Create Date: 2025-11-05 08:36:15.767537

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '758d4879be2e'
down_revision = '34a9930bd1f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'blob_processing_attempt',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_datetime', sa.DateTime(), nullable=False),
        sa.Column('updated_datetime', sa.DateTime(), nullable=True),
        sa.Column('blob_path', sa.String(), nullable=False),
        sa.Column('attempt_count', sa.Integer(), nullable=False, server_default='0'),
        sa.Column('last_error', sa.String(), nullable=True),
        sa.Column('last_attempt_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('blob_path')
    )
    op.create_index(op.f('ix_blob_processing_attempt_blob_path'), 'blob_processing_attempt', ['blob_path'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blob_processing_attempt_blob_path'), table_name='blob_processing_attempt')
    op.drop_table('blob_processing_attempt')
    # ### end Alembic commands ###