"""Add has_completed_onboarding to users

Revision ID: ed7aa9a4e0f2
Revises: d3ee506fc6d8
Create Date: 2025-09-16 12:19:52.644350

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'ed7aa9a4e0f2'
down_revision = 'd3ee506fc6d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'has_completed_onboarding')
    # ### end Alembic commands ###